version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: consentrajdbc-db
    restart: unless-stopped

    environment:
      POSTGRES_DB: consentrajdbc
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

    ports:
      - "5475:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d

volumes:
  postgres_data: