version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: jdbc-postgres
    restart: always
    environment:
      POSTGRES_DB: jdbcdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5465:5432"